<?php
/*
========================================
File: CourseSeeder.php

Description:
Seeds the database with courses data
including course codes, names, images,
languages, tools, and descriptions.

Author:
Nada Khaled

Notes:
- Each course belongs to a specific diploma section
  (AS, OR, MS, CS, EC, IT, DB, IS, OM, PP)
- Used to initialize the system with predefined academic courses
- It is recommended not to manually set IDs
========================================
*/
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use App\Models\Diploma;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'id' => '1',
                'code' => 'AS500',
                'img' => 'assets/images/diploma/subj/General/AS500.png',
                'name_ar' => 'الطرق الاحصائية',
                'name_en' => 'Statistical Methods',
                'language' => 'AR',
                'tools' => null,
                'description' => 'مقرر يشرح الأسس النظرية والتطبيقية للإحصاء الوصفي والاستدلالي. يتناول مفاهيم مثل المتوسطات والاختبارات الإحصائية. مع تدريب عملي على SPSS لتحليل البيانات.',
            ],
            [
                'id' => '2',
                'code' => 'OR500',
                'img' => 'assets/images/diploma/subj/General/OR500.png',
                'name_ar' => 'مقدمة فى بحوث العمليات',
                'name_en' => 'Introduction to Operations Research',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة أساسية تهدف إلى إكساب الطلاب الأدوات الرياضية الضرورية لدراسة النماذج الكمية وتطبيقاتها في الإحصاء وبحوث العمليات.',
            ],
            [
                'id' => '3',
                'code' => 'MS500',
                'img' => 'assets/images/diploma/subj/General/MS500.png',
                'name_ar' => 'طرق رياضية',
                'name_en' => 'Mathematical Methods',
                'language' => 'AR',
                'tools' => null,
                'description' => 'مقرر يهدف إلى تزويد الطالب بالأسس الرياضية اللازمة للدبلومات. يشمل موضوعات مثل المصفوفات، التفاضل والتكامل، والمعادلات التفاضلية.',
            ],
            [
                'id' => '4',
                'code' => 'CS500',
                'img' => 'assets/images/diploma/subj/General/CS500.png',
                'name_ar' => 'مقدمة فى علوم الحاسب',
                'name_en' => 'Introduction to Computer Sciences ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تمهيدية للتعرف على المفاهيم الأساسية في الحوسبة والبرمجيات. تتناول مكونات الحاسب المادية والبرمجية، إضافة إلى مبادئ أنظمة التشغيل.',
            ],
            [
                'id' => '5',
                'code' => 'DB500',
                'img' => 'assets/images/diploma/subj/General/DB500.png',
                'name_ar' => 'مقدمة فى الاحصاء الحيوى و السكانى',
                'name_en' => 'Introduction to Biostatistics & Demography ',
                'language' => 'AR',
                'tools' => null,
                'description' => 'مادة تشرح المفاهيم الأساسية للإحصاء التطبيقي في مجالات الصحة العامة والدراسات السكانية، وتطبيقاته في تحليل البيانات الطبية والديموغرافية.',
            ],
            //////////////////////////////////////AS///////////////////////////////////////////
            [
                'id' => '6',
                'code' => 'AS503',
                'img' => 'assets/images/diploma/subj/AS/AS503.png',
                'name_ar' => 'السلاسل الزمنية و تطبيقاتها',
                'name_en' => 'Time Series and its Applications',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يدرس البيانات الزمنية باستخدام نماذج مثل ARIMA لتحليل الاتجاهات والتنبؤ بالمستقبل.',
            ],
            [
                'id' => '7',
                'code' => 'AS506',
                'img' => 'assets/images/diploma/subj/AS/AS506.png',
                'name_ar' => 'التحليل الاحصائى',
                'name_en' => 'Statistical Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على تطبيق الأساليب الإحصائية في تحليل البيانات العملية باستخدام البرمجيات، مع تفسير النتائج في سياق علمي.',
            ],
            [
                'id' => '8',
                'code' => 'AS508',
                'img' => 'assets/images/diploma/subj/AS/AS508.png',
                'name_ar' => 'تحليل و تصميم التجارب 1',
                'name_en' => 'Design & Analysis of Experiments I ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح مبادئ تصميم التجارب الإحصائية وكيفية تحليل نتائجها لضمان دقة الاستنتاجات.',
            ],
            [
                'id' => '9',
                'code' => 'AS509',
                'img' => 'assets/images/diploma/subj/AS/AS509.png',
                'name_ar' => 'طرق المعاينة',
                'name_en' => 'Sampling Methods',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يعرض أساليب اختيار العينات المختلفة (عشوائية بسيطة، طبقية، عنقودية) وتطبيقاتها في البحوث الإحصائية.',
            ],
            [
                'id' => '10',
                'code' => 'AS511',
                'img' => 'assets/images/diploma/subj/AS/AS511.png',
                'name_ar' => 'تحليل الانحدار',
                'name_en' => 'Regression Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على النماذج الانحدارية لتفسير العلاقات بين المتغيرات والتنبؤ بالقيم المستقبلية.',
            ],
            [
                'id' => '11',
                'code' => 'AS517',
                'img' => 'assets/images/diploma/subj/AS/AS517.png',
                'name_ar' => 'الحاسبات الاحصائية و الرسومات',
                'name_en' => 'Statistical Computing & Graphics',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح كيفية استخدام البرمجيات الإحصائية لعرض البيانات وتحليلها باستخدام الجداول والرسوم البيانية.',
            ],
            [
                'id' => '12',
                'code' => 'AS521',
                'img' => 'assets/images/diploma/subj/AS/AS521.png',
                'name_ar' => 'مقدمة فى النماذج الخطية ',
                'name_en' => 'Introduction to Linear Models',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم الأسس النظرية للنماذج الخطية العامة وتطبيقاتها في تحليل التباين والانحدار.',
            ],
            [
                'id' => '13',
                'code' => 'AS528',
                'img' => 'assets/images/diploma/subj/AS/AS528.png',
                'name_ar' => 'تصميم و تحليل التجارب 2',
                'name_en' => 'Design & Analysis of Experiments II',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتعمق في تصميم التجارب المعقدة مثل المربعات اللاتينية والتحليل المتعدد العوامل.',
            ],
            //////////////////////////////////////OR///////////////////////////////////////////
            [
                'id' => '14',
                'code' => 'OR501',
                'img' => 'assets/images/diploma/subj/OR/OR501.png',
                'name_ar' => ' ادارة سلسلة الامداد',
                'name_en' => 'Supply Chain Management ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تركز المادة على المفاهيم الاساسية المتعلقة بتخطيط وادراة تدفقات البضائع والمواد والمعلومات فى النظام الانتاجى',
            ],
            [
                'id' => '15',
                'code' => 'OR502',
                'img' => 'assets/images/diploma/subj/OR/OR502.png',
                'name_ar' => 'نماذج التنبؤ ',
                'name_en' => 'Forecasting Model ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'نماذج التنبؤ وهو المجال الذى يركز على التنبؤ بالطلب والانتاج والمخزون وغيرها من جوانب العمليات المستقبلية بناء على بيانات تحليلية وتاريخية',
            ],
            [
                'id' => '16',
                'code' => 'OR505',
                'img' => 'assets/images/diploma/subj/OR/OR505.png',
                'name_ar' => 'االبرمجة الخطية',
                'name_en' => 'Linear Programming ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'البرمجة الخطية هى تقنية تحليلية تهدف الى تحسين (زيادة او تقليل) هدف معين - كربح او تكلفة ضمن قيود محددة',
            ],
            [
                'id' => '17',
                'code' => 'OR506',
                'img' => 'assets/images/diploma/subj/OR/OR506.png',
                'name_ar' => 'البرمجة الغير خطية',
                'name_en' => 'Nonlinear Programming ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تركز المادة على النماذج الرياضية والتحليلية التى لا تكون فيها العلاقات خطية . اى عندما تكون دالة الهدف او بعض القيود غير خطية .',
            ],
            [
                'id' => '18',
                'code' => 'OR507',
                'img' => 'assets/images/diploma/subj/OR/OR507.png',
                'name_ar' => 'الشبكات',
                'name_en' => 'Networks ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تقدم نماذج شبكية مثل أقصر مسار، التدفق الأقصى، ومشاكل النقل، مع تطبيقات عملية.',
            ],
            [
                'id' => '19',
                'code' => 'OR508',
                'img' => 'assets/images/diploma/subj/OR/OR508.png',
                'name_ar' => 'النمذجة و المحاكاة',
                'name_en' => 'Modeling  & Simulation ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على بناء النماذج الرياضية والمحاكاة لفهم وتحليل الانظمة المعقدة فى مجال الادارة والعمليات . عندما يصعب او يستحيل ايجاد حلول تحليلية مباشرة.',
            ],
            [
                'id' => '20',
                'code' => 'OR509',
                'img' => 'assets/images/diploma/subj/OR/OR509.png',
                'name_ar' => ' التحليل الاقتصادى للنظم 1',
                'name_en' => 'Economics Analysis of Systems I',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح الأساليب الكمية لتقييم النظم ومقارنتها من حيث الكفاءة الاقتصادية.',
            ],
            [
                'id' => '21',
                'code' => 'OR511',
                'img' => 'assets/images/diploma/subj/OR/OR511.png',
                'name_ar' => 'ادارة المخزون ',
                'name_en' => 'Inventory Management',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم أساليب تخطيط المخزون، سياسات الطلب، وتقليل التكاليف المرتبطة بالمخزون.',
            ],
            [
                'id' => '22',
                'code' => 'OR512',
                'img' => 'assets/images/diploma/subj/OR/OR512.png',
                'name_ar' => 'موضوعات مختارة فى بحوث العمليات ',
                'name_en' => 'Selected Topics in Operations Research',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يعرض أحدث التطبيقات والاتجاهات الحديثة في مجال بحوث العمليات.',
            ],
            [
                'id' => '23',
                'code' => 'OR513',
                'img' => 'assets/images/diploma/subj/OR/OR513.png',
                'name_ar' => ' المباريات و نظرية القرار ',
                'name_en' => 'Games and Decision Theory',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تقدم أسس نظرية الألعاب واتخاذ القرارات في مواقف تتضمن منافسة أو عدم يقين.',
            ],
            [
                'id' => '24',
                'code' => 'OR514',
                'img' => 'assets/images/diploma/subj/OR/OR514.png',
                'name_ar' => 'توكيد الجود ',
                'name_en' => 'Quality Assurance',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على استراتيجيات ضمان الجودة وتحسين العمليات باستخدام أدوات إحصائية.',
            ],
            [
                'id' => '25',
                'code' => 'OR515',
                'img' => 'assets/images/diploma/subj/OR/OR515.png',
                'name_ar' => 'ادارة المشروعات',
                'name_en' => 'Project Management ',

                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على مفاهيم وادوات واساليب ادارة المشروعات . بدءاً من التخطيط وحتى التنفيذ والتابعة والتقييم',
            ],
            [
                'id' => '26',
                'code' => 'OR516',
                'img' => 'assets/images/diploma/subj/OR/OR516.png',
                'name_ar' => 'نظرية الصفوف ',
                'name_en' => 'Queuing Theory',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تدرس نماذج الانتظار وتحليلها لتقليل وقت الانتظار وتحسين الخدمات.',
            ],
            [
                'id' => '27',
                'code' => 'OR526',
                'img' => 'assets/images/diploma/subj/OR/OR526.png',
                'name_ar' => ' البرمجة غير الخطية 2',
                'name_en' => 'Nonlinear Programming II ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تركز على طرق تقريب الحلول للمسائل الرياضية. الأساليب العددية للجبر',
            ],
            [
                'id' => '28',
                'code' => 'OR529',
                'img' => 'assets/images/diploma/subj/OR/OR529.png',
                'name_ar' => 'التحليل الاقتصادى للنظم 2 ',
                'name_en' => 'Economic Analysis of Systems II',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على التحليل المتقدم للنظم باستخدام النماذج الكمية والتقييم الاقتصادي.',
            ],
            //////////////////////////////////////MS///////////////////////////////////////////
            [
                'id' => '29',
                'code' => 'MS505',
                'img' => 'assets/images/diploma/subj/MS/MS505.png',
                'name_ar' => 'رياضيات متقدمة ',
                'name_en' => ' Advanced Mathematics',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتناول موضوعات رياضية متقدمة مثل المصفوفات، التكامل المتعدد، والمعادلات التفاضلية، كأساس لفهم المناهج الإحصائية والاقتصادية.',
            ],
            [
                'id' => '30',
                'code' => 'MS506',
                'img' => 'assets/images/diploma/subj/MS/MS506.png',
                'name_ar' => 'جبر خطى  ',
                'name_en' => 'Linear Algebra ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح مفاهيم الجبر الخطي مثل المصفوفات والمتجهات ونظم المعادلات الخطية وتطبيقاتها في الإحصاء.',
            ],
            [
                'id' => '31',
                'code' => 'MS507',
                'img' => 'assets/images/diploma/subj/MS/MS507.png',
                'name_ar' => ' الاحتمالات و التوزيعات الاحصائية 1',
                'name_en' => ' Probability &Statistical Distributions I ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم المفاهيم الأساسية لنظرية الاحتمالات والتوزيعات الاحتمالية، كأساس لبناء النماذج الإحصائية.',
            ],
            [
                'id' => '32',
                'code' => 'MS512',
                'img' => 'assets/images/diploma/subj/MS/MS512.png',
                'name_ar' => 'تحليل بيزى ',
                'name_en' => ' Bayesian Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم منهجية بايز في الاستدلال الإحصائي باستخدام الاحتمالات الشرطية لدمج البيانات مع المعلومات السابقة.',
            ],
            [
                'id' => '33',
                'code' => 'MS513',
                'img' => 'assets/images/diploma/subj/MS/MS513.png',
                'name_ar' => 'الاحصائات الترتيبية  ',
                'name_en' => ' Order Statistics',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على أساليب تحليل البيانات المرتبة مثل الوسيط، الرتب، والاختبارات غير المعلمية.',
            ],
            [
                'id' => '34',
                'code' => 'MS514',
                'img' => 'assets/images/diploma/subj/MS/MS514.png',
                'name_ar' => 'الاستدلال الاححصائى 1 ',
                'name_en' => ' Statistical Inference I',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم مفاهيم التقدير بفترات الثقة والاختبارات الإحصائية الأساسية لاستنتاج النتائج من البيانات.',
            ],
            [
                'id' => '35',
                'code' => 'MS517',
                'img' => 'assets/images/diploma/subj/MS/MS517.png',
                'name_ar' => ' مقدمة فى التحليل العددى',
                'name_en' => ' Introduction to Numerical Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتناول طرقًا تقريبية لحل المعادلات الرياضية مثل طرق نيوتن والتكامل العددي، باستخدام الحاسب.',
            ],
            [
                'id' => '36',
                'code' => 'MS518',
                'img' => 'assets/images/diploma/subj/MS/MS518.png',
                'name_ar' => 'مراقبة الجودة الاحصائية ',
                'name_en' => 'Statistical Quality Control ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح أدوات مراقبة الجودة مثل خرائط السيطرة الإحصائية وتحليل العمليات لتحسين الأداء الصناعي.',
            ],
            [
                'id' => '37',
                'code' => 'MS521',
                'img' => 'assets/images/diploma/subj/MS/MS521.png',
                'name_ar' => 'تراكيب محددة ',
                'name_en' => ' Discrete Structures',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة متقدمة في تصميم المترجمات مع التركيز على التركيب النحوي. تتناول خوارزميات تحليل اللغات الرسمية وتركيبها.',
            ],
            [
                'id' => '38',
                'code' => 'MS524',
                'img' => 'assets/images/diploma/subj/MS/MS524.png',
                'name_ar' => 'الاستدلال الاحصائى 2 ',
                'name_en' => ' Statistical Inference II',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتعمق في طرق الاستدلال المتقدمة مثل الاختبارات المعلمية وغير المعلمية وتحليل التباين.',
            ],
            [
                'id' => '39',
                'code' => 'MS527',
                'img' => 'assets/images/diploma/subj/MS/MS527.png',
                'name_ar' => 'الاحتمالات و التوزيعات الاحصائية 2 ',
                'name_en' => 'Probability &Statistical Distributions II  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتوسع في دراسة التوزيعات الاحتمالية المتعددة والمتقدمة ونظرياتها الرياضية.',
            ],

            ///////////////////////////////////////DB//////////////////////////////////////////
            [
                'id' => '40',
                'code' => 'DB501',
                'img' => 'assets/images/diploma/subj/DB/DB501.png',
                'name_ar' => 'مفاهيم و مقاييس الانجاب ',
                'name_en' => 'Fertility Concepts and Measures',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '41',
                'code' => 'DB502',
                'img' => 'assets/images/diploma/subj/DB/DB502.png',
                'name_ar' => 'مفاهيم و مقاييس الوفيات ',
                'name_en' => 'Concepts and Measures of Mortality',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '42',
                'code' => 'DB503',
                'img' => 'assets/images/diploma/subj/DB/DB503.png',
                'name_ar' => ' الهجرة و التحضر',
                'name_en' => 'Migration & Urbanization ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '43',
                'code' => 'DB505',
                'img' => 'assets/images/diploma/subj/DB/DB505.png',
                'name_ar' => ' تنظيم الاسرة و موضوعات مرتبطة',
                'name_en' => 'Family Planning and Related Topics',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '44',
                'code' => 'DB506',
                'img' => 'assets/images/diploma/subj/DB/DB506.png',
                'name_ar' => ' نماذج سكانية ',
                'name_en' => 'Demographic Models',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '45',
                'code' => 'DB507',
                'img' => 'assets/images/diploma/subj/DB/DB507.png',
                'name_ar' => 'اساسيات التحليل الديموجرافى ',
                'name_en' => 'Demographic Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '46',
                'code' => 'DB508',
                'img' => 'assets/images/diploma/subj/DB/DB508.png',
                'name_ar' => ' احصاء حيوى',
                'name_en' => 'Biostatistics ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '47',
                'code' => 'DB509',
                'img' => 'assets/images/diploma/subj/DB/DB509.png',
                'name_ar' => 'الصحة الانجابية ',
                'name_en' => 'Reproductive Health',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '48',
                'code' => 'DB511',
                'img' => 'assets/images/diploma/subj/DB/DB511.png',
                'name_ar' => ' المسوح السكانية',
                'name_en' => 'Demographic Surveys',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '49',
                'code' => 'DB512',
                'img' => 'assets/images/diploma/subj/DB/DB512.png',
                'name_ar' => ' جودة و ادارة البرامج السكانية ',
                'name_en' => 'Quality of Population Programs ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '50',
                'code' => 'DB513',
                'img' => 'assets/images/diploma/subj/DB/DB513.png',
                'name_ar' => 'التعمير السكانى ',
                'name_en' => 'Aging of Populations',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '51',
                'code' => 'DB514',
                'img' => 'assets/images/diploma/subj/DB/DB514.png',
                'name_ar' => 'قضايا النوع الاجتماعى فى الدراسات السكانية ',
                'name_en' => 'Gender Issuesin Population Studies',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '52',
                'code' => 'DB516',
                'img' => 'assets/images/diploma/subj/DB/DB516.png',
                'name_ar' => 'تحليل بيانات البقاء ',
                'name_en' => 'Survival Data Analysis',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '53',
                'code' => 'DB517',
                'img' => 'assets/images/diploma/subj/DB/DB517.png',
                'name_ar' => 'تنمية بشرية ',
                'name_en' => 'Human Development',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '54',
                'code' => 'DB518',
                'img' => 'assets/images/diploma/subj/DB/DB518.png',
                'name_ar' => 'السكان و التنمية ',
                'name_en' => 'Population and Development ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '55',
                'code' => 'DB528',
                'img' => 'assets/images/diploma/subj/DB/DB528.png',
                'name_ar' => 'احصاء حيوى متقدم ',
                'name_en' => 'Advanced Biostatistics',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            ///////////////////////////////////////IT//////////////////////////////////////////
            [
                'id' => '56',
                'code' => 'IT500',
                'img' => 'assets/images/diploma/subj/IT/IT500.png',
                'name_ar' => ' مبادئ نظم المعلومات',
                'name_en' => ' Information systems Principles',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '57',
                'code' => 'IT501',
                'img' => 'assets/images/diploma/subj/IT/IT501.png',
                'name_ar' => ' تطوير نظم المعلومات 1',
                'name_en' => 'Information Systems Development I ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '58',
                'code' => 'IT502',
                'img' => 'assets/images/diploma/subj/IT/IT502.png',
                'name_ar' => 'تصميم الوسائط المتعددة لنظم المعلومات ',
                'name_en' => 'Multimedia Design for Information Systems ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '59',
                'code' => 'IT503',
                'img' => 'assets/images/diploma/subj/IT/IT503.png',
                'name_ar' => ' تحليل و تصميم النظم',
                'name_en' => 'Systems Analysis & Design ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '60',
                'code' => 'IT504',
                'img' => 'assets/images/diploma/subj/IT/IT504.png',
                'name_ar' => ' نظم المعلومات الادارية',
                'name_en' => ' Management Information Systems',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '61',
                'code' => 'IT505',
                'img' => 'assets/images/diploma/subj/IT/IT505.png',
                'name_ar' => ' تفاعل الحاسب و الانسان',
                'name_en' => 'Human –Computer Interaction ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '62',
                'code' => 'IT508',
                'img' => 'assets/images/diploma/subj/IT/IT508.png',
                'name_ar' => 'تطوير برمجيات لشبكة الانترنت ',
                'name_en' => 'Web Application  Development ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '63',
                'code' => 'IT510',
                'img' => 'assets/images/diploma/subj/IT/IT510.png',
                'name_ar' => 'التجارة الالكترونية ',
                'name_en' => ' Electronic Commerce',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '64',
                'code' => 'IT511',
                'img' => 'assets/images/diploma/subj/IT/IT511.png',
                'name_ar' => 'ادارة نظم المعلومات ',
                'name_en' => ' Managing the Impact of Information Systems ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '65',
                'code' => 'IT512',
                'img' => 'assets/images/diploma/subj/IT/IT512.png',
                'name_ar' => ' الاطر القانونية و الاخلاقية لنظم المعلومات',
                'name_en' => ' Legal & Ethical Frameworks of Information Systems',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '66',
                'code' => 'IT513',
                'img' => 'assets/images/diploma/subj/IT/IT513.png',
                'name_ar' => 'نظم المعلومات فى سوق المال ',
                'name_en' => ' Information Technology in Financial Market ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '67',
                'code' => 'IT514',
                'img' => 'assets/images/diploma/subj/IT/IT514.png',
                'name_ar' => ' تكامل تكنولوجيا المعلومات فى الاعمال التجارية',
                'name_en' => 'Integrating Information Technologies & Business Process  ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '68',
                'code' => 'IT515',
                'img' => 'assets/images/diploma/subj/IT/IT515.png',
                'name_ar' => ' التطبيقات التجارية لتكنولوجيا النظم الخبيرة',
                'name_en' => ' Business Applications of Expert Systems Technology ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '69',
                'code' => 'IT516',
                'img' => 'assets/images/diploma/subj/IT/IT516.png',
                'name_ar' => ' موضوعات مختارة فى تكنولوجيا المعلومات',
                'name_en' => 'Selected Topics in Information Technology ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '70',
                'code' => 'IT517',
                'img' => 'assets/images/diploma/subj/IT/IT517.png',
                'name_ar' => 'امن المعلومات ',
                'name_en' => ' Information Security',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '71',
                'code' => 'IT518',
                'img' => 'assets/images/diploma/subj/IT/IT518.png',
                'name_ar' => 'تقييم نظم المعلومات ',
                'name_en' => ' Evaluation of Information Systems',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '72',
                'code' => 'IT519',
                'img' => 'assets/images/diploma/subj/IT/IT519.png',
                'name_ar' => 'قواعد البيانات الشيئية ',
                'name_en' => 'Object Oriented Databases ',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            [
                'id' => '73',
                'code' => 'IT521',
                'img' => 'assets/images/diploma/subj/IT/IT521.png',
                'name_ar' => 'تطوير نظم المعلومات 2 ',
                'name_en' => ' Information Systems Development II',
                'language' => 'EN',
                'tools' => null,
                'description' => null,
            ],
            ///////////////////////////////////////CS//////////////////////////////////////////
            [
                'id' => '74',
                'code' => 'CS503',
                'img' => 'assets/images/diploma/subj/CS/CS503.png',
                'name_ar' => 'برمجة الحاسب 1 ',
                'name_en' => ' Computer Programming I',
                'language' => 'EN',
                'tools' => 'C++',
                'description' => 'تعرف الطالب على أساسيات البرمجة باستخدام إحدى لغات البرمجة عالية المستوى، مع التدريب على كتابة برامج لحل مشكلات عملية.',
            ],
            [
                'id' => '75',
                'code' => 'CS504',
                'img' => 'assets/images/diploma/subj/CS/CS504.png',
                'name_ar' => 'المنطق الرقمى و تنظيم الحاسبات ',
                'name_en' => ' Digital Logic & Computer Organization',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يتناول المبادئ الأساسية للمنطق الرقمي وتصميم الدوائر المنطقية. كما يشرح بنية الحاسب الداخلية وتنظيم مكوناته ووظائفها.',
            ],
            [
                'id' => '76',
                'code' => 'CS505',
                'img' => 'assets/images/diploma/subj/CS/CS505.png',
                'name_ar' => ' هياكل البيانات و الخورزميات',
                'name_en' => ' Data Structures &Algorithms',
                'language' => 'EN',
                'tools' => 'C++',
                'description' => 'يعرض مفاهيم هياكل البيانات مثل القوائم والأشجار والمكدسات والطوابير. ويوضح كيفية بناء الخوارزميات وتحليل كفاءتها.',
            ],
            [
                'id' => '77',
                'code' => 'CS506',
                'img' => 'assets/images/diploma/subj/CS/CS506.png',
                'name_ar' => 'نظم التشغيل  ',
                'name_en' => 'Operating Systems ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقدمة في الأسس النظرية والعملية لنظم التشغيل ودورها في إدارة الموارد. تتناول إدارة العمليات والذاكرة ونظم الملفات.',
            ],
            [
                'id' => '78',
                'code' => 'CS507',
                'img' => 'assets/images/diploma/subj/CS/CS507.png',
                'name_ar' => 'نظم قواعد البيانات 1  ',
                'name_en' => ' Database Systems I',
                'language' => 'EN',
                'tools' => 'SQL',
                'description' => 'يدرس تصميم وبناء وإدارة قواعد البيانات باستخدام النموذج العلائقي. مع التركيز على لغة الاستعلام SQL لتطبيقات عملية.',
            ],
            [
                'id' => '79',
                'code' => 'CS508',
                'img' => 'assets/images/diploma/subj/CS/CS508.png',
                'name_ar' => 'هندسة البرمجيات 1 ',
                'name_en' => ' Software Engineering I',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يشرح دورة حياة تطوير البرمجيات ونماذج وأساليب التحليل والتصميم. يهدف إلى بناء أنظمة برمجية كبيرة بشكل منظم وفعال.',
            ],
            [
                'id' => '80',
                'code' => 'CS509',
                'img' => 'assets/images/diploma/subj/CS/CS509.png',
                'name_ar' => 'شبكات الحاسب ',
                'name_en' => ' Computer Networks',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقدمة في أسس شبكات الحاسب ونماذج الاتصال مثل OSI وTCP/IP. تتناول بروتوكولات الاتصال وتقنيات نقل البيانات.',
            ],
            [
                'id' => '81',
                'code' => 'CS510',
                'img' => 'assets/images/diploma/subj/CS/CS510.png',
                'name_ar' => ' بناء المترجمات',
                'name_en' => 'Compiler Construction ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم الأسس النظرية لبناء المترجمات بمراحلها المختلفة. يشمل التحليل اللغوي والدلالي وتوليد الشفرة الخاصة بالحاسوب.',
            ],
            [
                'id' => '82',
                'code' => 'CS511',
                'img' => 'assets/images/diploma/subj/CS/CS511.png',
                'name_ar' => ' مبادئ الذكاء الاصطناعى',
                'name_en' => 'Introduction to Artificial Intelligence  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر يقدم الأسس النظرية لتقنيات الذكاء الاصطناعي. يشمل البحث، الاستدلال، وتمثيل المعرفة لحل المشكلات.',
            ],
            [
                'id' => '83',
                'code' => 'CS512',
                'img' => 'assets/images/diploma/subj/CS/CS512.png',
                'name_ar' => 'تصميم و تحليل الخورزميات ',
                'name_en' => 'Design & Analysis of  Algorithms ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تركز على بناء خوارزميات فعّالة لحل المشكلات. تهتم بتحليل التعقيد الزمني والفضائي للخوارزميات.',
            ],
            [
                'id' => '84',
                'code' => 'CS513',
                'img' => 'assets/images/diploma/subj/CS/CS513.png',
                'name_ar' => 'عمارة الحاسب ',
                'name_en' => ' Computer Architecture',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر يشرح المكونات الداخلية للحاسب وكيفية عملها. يتناول المعالجات، الذاكرة، والتنظيم المعماري للحواسيب.',
            ],
            [
                'id' => '85',
                'code' => 'CS514',
                'img' => 'assets/images/diploma/subj/CS/CS514.png',
                'name_ar' => ' الاتوماتا و اللغات الصورية',
                'name_en' => 'Formal Language & Automata  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تهدف إلى دراسة النماذج الرياضية للحوسبة. تتناول الآلات المحدودة، اللغات الرسمية، والنحو.',
            ],
            [
                'id' => '86',
                'code' => 'CS515',
                'img' => 'assets/images/diploma/subj/CS/CS515.png',
                'name_ar' => 'موضوعات مختارة فى علوم الحاسب  ',
                'name_en' => ' Selected Topics in Computer Science ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر مرن يطرح موضوعات متقدمة وحديثة في التخصص. يساعد الطالب على الاطلاع على آخر اتجاهات البحث.',
            ],
            [
                'id' => '87',
                'code' => 'CS516',
                'img' => 'assets/images/diploma/subj/CS/CS516.png',
                'name_ar' => 'لغة الاسمبلى ',
                'name_en' => 'Assembly Language Programming  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تعرف الطالب بالبرمجة منخفضة المستوى. تربط بين البرمجيات والأوامر المباشرة للمعالج.',
            ],
            [
                'id' => '88',
                'code' => 'CS517',
                'img' => 'assets/images/diploma/subj/CS/CS517.png',
                'name_ar' => ' رسومات الحاسب',
                'name_en' => ' Computer Graphics',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر يعرض أساسيات الرسوميات ثنائية وثلاثية الأبعاد. يشمل تقنيات الإظهار، التحويلات، والمعالجة الرسومية.',
            ],
            [
                'id' => '89',
                'code' => 'CS518',
                'img' => 'assets/images/diploma/subj/CS/CS518.png',
                'name_ar' => ' برمجة الوسائط المتعددة',
                'name_en' => 'Multimedia Computing  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تركز على دمج الصوت، الفيديو، والصور في البرمجة. تشمل تقنيات التفاعل والتطبيقات متعددة الوسائط.',
            ],
            [
                'id' => '90',
                'code' => 'CS519',
                'img' => 'assets/images/diploma/subj/CS/CS519.png',
                'name_ar' => 'التحليل و التصميم شيئ التوجية  ',
                'name_en' => 'Object-Oriented Analysis & Design ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر يقدم أساليب بناء الأنظمة باستخدام البرمجة الكائنية. يشمل مخططات UML ومفاهيم الوراثة والتجريد.',
            ],
            [
                'id' => '91',
                'code' => 'CS520',
                'img' => 'assets/images/diploma/subj/CS/CS520.png',
                'name_ar' => ' نظم قواعد المعرفة',
                'name_en' => 'Knowledge-Base Systems ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تهدف إلى تصميم أنظمة تستند إلى المعرفة. تركز على التمثيل المنطقي والاستنتاج في الخبرة.',
            ],
            [
                'id' => '92',
                'code' => 'CS521',
                'img' => 'assets/images/diploma/subj/CS/CS521.png',
                'name_ar' => 'معالجة الاشارات الرقمية  ',
                'name_en' => ' Digital Signal Processing',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر يتناول طرق تحليل وتحويل الإشارات. يشمل الفلاتر، تحويل فورييه، وتطبيقات متعددة.',
            ],
            [
                'id' => '93',
                'code' => 'CS522',
                'img' => 'assets/images/diploma/subj/CS/CS522.png',
                'name_ar' => ' برمجة الحاسب لبحوث العمليات',
                'name_en' => ' Computer Programming for Operations Research ',
                'language' => 'EN',
                'tools' => 'Python',
                'description' => 'توضح كيفية استخدام لغات البرمجة في بناء وحل نماذج بحوث العمليات.',
            ],
            [
                'id' => '94',
                'code' => 'CS523',
                'img' => 'assets/images/diploma/subj/CS/CS523.png',
                'name_ar' => ' برمجة الحاسب 2',
                'name_en' => ' Computer Programming II',
                'language' => 'EN',
                'tools' => 'Java',
                'description' => 'استكمال لمقرر برمجة الحاسب I بتعمق أكبر. يتناول الهياكل المعقدة والخوارزميات المتقدمة.',
            ],
            [
                'id' => '95',
                'code' => 'CS526',
                'img' => 'assets/images/diploma/subj/CS/CS526.png',
                'name_ar' => ' برمجة النظم',
                'name_en' => ' Systems Programming',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تركز على البرمجة المرتبطة بأنظمة التشغيل. تشمل إدارة العمليات، الذاكرة، وملفات النظام.',
            ],
            [
                'id' => '96',
                'code' => 'CS527',
                'img' => 'assets/images/diploma/subj/CS/CS527.png',
                'name_ar' => ' قواعد البيانات 2',
                'name_en' => ' Database  System II',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر متقدم في تصميم وإدارة قواعد البيانات. يتناول تحسين الاستعلامات والأنظمة الموزعة.',
            ],
            [
                'id' => '97',
                'code' => 'CS531',
                'img' => 'assets/images/diploma/subj/CS/CS531.png',
                'name_ar' => 'اساسيات لغات الحاسب ',
                'name_en' => ' Principles of Programming Languages',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تشرح المفاهيم العامة لبناء لغات البرمجة. تشمل النحو، الدلالات، وآليات التنفيذ.',
            ],
            ///////////////////////////////////////EC//////////////////////////////////////////
            [
                'id' => '98',
                'code' => 'EC505',
                'img' => 'assets/images/diploma/subj/EC/EC505.png',
                'name_ar' => ' اقتصاد قياسى 1',
                'name_en' => ' Econometrics I ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم الأسس النظرية والتطبيقية لبناء النماذج الاقتصادية باستخدام البيانات الإحصائية، مع التركيز على تحليل الانحدار البسيط والمتعدد.',
            ],
            [
                'id' => '99',
                'code' => 'EC508',
                'img' => 'assets/images/diploma/subj/EC/EC508.png',
                'name_ar' => 'الطرق الرياضية فى التحليل الاقتصادى ',
                'name_en' => 'Mathematical Methods for Economic Analysis ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يقدم أدوات رياضية لتحليل المشكلات الاقتصادية وتطبيق نماذج كمية لفهم القرارات الاقتصادية.',
            ],
            [
                'id' => '100',
                'code' => 'EC510',
                'img' => 'assets/images/diploma/subj/EC/EC510.png',
                'name_ar' => ' الاقتصاد الرياضى',
                'name_en' => ' Mathematical Economics ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'يركز على استخدام الأساليب الرياضية لتمثيل وتحليل الظواهر الاقتصادية في صورة معادلات ونماذج.',
            ],
            [
                'id' => '101',
                'code' => 'EC525',
                'img' => 'assets/images/diploma/subj/EC/EC525.png',
                'name_ar' => 'اقتصاد قياسى 2 ',
                'name_en' => ' Econometrics II ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مادة تركز على البرمجة المرتبطة بأنظمة التشغيل. تشمل إدارة العمليات، الذاكرة، وملفات النظام.',
            ],
            ///////////////////////////////////////IS//////////////////////////////////////////
            [
                'id' => '102',
                'code' => 'IS508',
                'img' => 'assets/images/diploma/subj/IS/IS508.png',
                'name_ar' => ' تطوير تطبيقات شبكة الانترنت',
                'name_en' => 'Web Applications Development  ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'بتعرف الطالب علي كيفية تصميم و تطوير مواقع الويب والتعامل مع تطبيقات الانترنت وتكون قادر تبنب انظمة معلومات تعمل عبر الانترنت بشكل امن وفعال.',
            ],
            [
                'id' => '103',
                'code' => 'IS509',
                'img' => 'assets/images/diploma/subj/IS/IS509.png',
                'name_ar' => 'ادارة مراكز المعلومات ',
                'name_en' => ' Management of Information Centers',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تاهيل الطالب لفهم كيفية ادارة و تشغيل مراكز المعلومات بكفاءة من حيث البنية التحتية والموارد البشرية والامن بحيث يقدر يشتغل في مجالات ادارة قواعدة البيانات وادارة الشبكات .',
            ],
            ///////////////////////////////////////OM//////////////////////////////////////////
            [
                'id' => '104',
                'code' => 'OM500',
                'img' => 'assets/images/diploma/subj/OM/OM500.png',
                'name_ar' => 'مبادئ ادارة العمليات ',
                'name_en' => ' Principles of Operations Management',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تدرس المادة مقدمة عن ادارة العمليات. تصميم العمليات والانتاج . ادارة الموارد. ادارة سلاسل الامداد . الجودة والتحسين المستمر',
            ],
            [
                'id' => '105',
                'code' => 'OM504',
                'img' => 'assets/images/diploma/subj/OM/OM504.png',
                'name_ar' => 'رقابة المخزون ',
                'name_en' => ' Quality Control',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على ادارة علمليات لاانتاج والمخزون ,وكيفية تحقيق التوازن بين الطلب والمواد المتاحة , وهى من المواد التطبيقية جدا فى مجال ادارة العمليات',
            ],
            [
                'id' => '106',
                'code' => 'OM505',
                'img' => 'assets/images/diploma/subj/OM/OM505.png',
                'name_ar' => 'تحليل اقتصادى ',
                'name_en' => 'Economic Analysis ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تركز المادة على ادارة وتشغيل الانشطة الخدمية , الهدف هو تحسين الكفاءة والجودة فى قطاع الخدمات',
            ],
            [
                'id' => '107',
                'code' => 'OM506',
                'img' => 'assets/images/diploma/subj/OM/OM506.png',
                'name_ar' => 'تخطيط احتياجات الموارد ',
                'name_en' => ' Material Requirement Planning',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على المفاهيم والأساليب الخاصة بضمان الجودة وتحسينها فى المؤسسات الإنتاجية والخدمية',
            ],
            [
                'id' => '108',
                'code' => 'OM507',
                'img' => 'assets/images/diploma/subj/OM/OM507.png',
                'name_ar' => ' ادارة الانتاج',
                'name_en' => 'Production Management ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على إدارة تدفق المواد والمعلومات والموارد عبر جميع مراحل سلسلة الامداد , من الموردين حتى المستهلك النهائى',
            ],
            [
                'id' => '109',
                'code' => 'OM508',
                'img' => 'assets/images/diploma/subj/OM/OM508.png',
                'name_ar' => 'موضوعات مختارة فى ادارة العمليات ',
                'name_en' => ' Selected Topics in Operations Management',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على الجانب الاستراتيجى لأدارة العمليات , اى كيف يتم ربط قرارات العمليات برؤية المؤسسة واهدافها التنافسية طويلة المدى',
            ],
            [
                'id' => '110',
                'code' => 'OM509',
                'img' => 'assets/images/diploma/subj/OM/OM509.png',
                'name_ar' => ' مشاكل النقل',
                'name_en' => 'Transportation Problems ',
                'language' => 'EN',
                'tools' => null,
                'description' => 'المادة تركز على كيفية استخدام النظم والبرمجيات لمساعدة المديرين وصناع القرار فى حل المشكلات المعقدة واتخاذ قرارات افضل',
            ],
            ///////////////////////////////////////PP//////////////////////////////////////////
            [
                'id' => '111',
                'code' => 'PP501',
                'img' => 'assets/images/diploma/subj/PP/PP501.png',
                'name_ar' => 'مهارات اعداد المشروع',
                'name_en' => 'Project Preparation Skills',
                'language' => 'EN',
                'tools' => null,
                'description' => 'تساعد الطالب على تعلم طرق البحث العلمي وإعداد الوثائق. كما تعزز مهارات العرض والتواصل والعمل ضمن فريق.',
            ],
            [
                'id' => '112',
                'code' => 'PP502',
                'img' => 'assets/images/diploma/subj/PP/PP502.png',
                'name_ar' => 'مشروع',
                'name_en' => 'Project',
                'language' => 'EN',
                'tools' => null,
                'description' => 'مقرر تطبيقي يجمع ما درسه الطالب طوال فترة الدبلوم. يشمل تصميم وتنفيذ مشروع متكامل يحاكي نظامًا واقعيًا.',
            ],
        ];
        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
